package expo.modules.auctioncamera.model

data class ExifData(
    val orientation: Int? = null,
    val gpsLatitude: String?          = null,
    val gpsLatitudeRef: String?       = null,
    val gpsLongitude: String?         = null,
    val gpsLongitudeRef: String?      = null,
    val gpsAltitude: String?          = null,
    val gpsAltitudeRef: String?       = null,
    val gpsTimestamp: String?         = null,
    val gpsDateStamp: String?         = null,
    val gpsSpeed: String?             = null,
    val gpsSpeedRef: String?          = null,
    val gpsBearing: String?           = null,
    val gpsBearingRef: String?        = null,
    val gpsProcessingMethod: String?  = null,
    val dateTime: String?             = null,
    val dateTimeOriginal: String?     = null,
    val dateTimeDigitized: String?    = null,
    val offsetTime: String?           = null,
    val make: String?                 = null,
    val model: String?                = null,
    val software: String?             = null,
    val isoSpeedRatings: String?      = null,
    val exposureTime: String?         = null,
    val fNumber: String?              = null,
    val focalLength: String?          = null,
    val focalLengthIn35mm: String?    = null,
    val flash: String?                = null,
    val whiteBalance: String?         = null,
    val exposureMode: String?         = null,
    val exposureBiasValue: String?    = null,
    val meteringMode: String?         = null,
    val sceneCaptureType: String?     = null,
    val imageWidth: String?           = null,
    val imageLength: String?          = null,
    val pixelXDimension: String?      = null,
    val pixelYDimension: String?      = null,
) {
    val hasGps: Boolean get() = gpsLatitude != null && gpsLongitude != null
}
