plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
  id 'org.jetbrains.kotlin.android'
}
group = 'expo.modules.reporttransfer'
version = '1.0.0'
android {
  namespace 'expo.modules.reporttransfer'
  compileSdk rootProject.ext.compileSdkVersion
  defaultConfig {
    minSdk 24
    versionCode 1
    versionName '1.0.0'
    testInstrumentationRunner 'expo.modules.reporttransfer.TransferInstrumentation'
  }
  compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
  kotlinOptions { jvmTarget = '17' }
}
dependencies {
  implementation 'androidx.work:work-runtime:2.12.0'
  implementation 'com.squareup.okhttp3:okhttp:4.12.0'
}
